Docs for Windows, new .gitattributes file and some SDM pipeline mods
GEO-BON/biab-2.0 pull request #71
Opened 2023-08-21 15:52 UTC by frousseu

Some edits in the README for Windows users (virtualization), new .gitattributes files to always have files with eol=lf and some modifications in the SDM pipeline for default values and how the range is obtained through the faster quantile function

2023-08-21 17:51 UTC, jmlord requested changes

2023-08-21 17:51 UTC, jmlord commented on .gitattributes
Je pense qu'on devrait régler les questions en suspens avant le merge. D'après ma lecture, on serait peut-être correct avec ceci: 
```
# Auto detect text files and perform LF normalization https://tsalikis.blog/posts/gitattributes/
# Also https://delitescere.medium.com/docker-file-permissions-and-line-endings-9aced07d70f8
* text eol=lf

# Any Windows file should be kept to crlf
*.bat	text eol=crlf
*.cmd	text eol=crlf
```

Pourrais-tu faire le test stp?

2023-08-21 17:51 UTC, jmlord commented on pipelines/SDM/SDM_maxEnt.json
> +        "value": "\n"
oups, il restait un \n. Devrait être null.

2023-08-21 17:51 UTC, jmlord commented on scripts/SDM/rangePredictions.yml
> +description: "This script computes the range of a 95% CI of a set of predictions rasters (from different models or from bootstrap/cross-validation procedures)."
C'est quoi CI?

2023-08-21 17:51 UTC, jmlord commented on scripts/SDM/rangePredictionsFunc.R
> +    return(range)
Est-ce que ceci a réparé rangePredictions?

2023-08-21 18:27 UTC, frousseu commented on pipelines/SDM/SDM_maxEnt.json
> +        "value": "\n"
removed

2023-08-21 18:32 UTC, frousseu commented on scripts/SDM/rangePredictionsFunc.R
> +    return(range)
Je ne dirais pas que range_predictions était brisée, mais l'utilisation de la fonction quantile du package terra est beaucoup plus rapide que l'utilisation de la fonction app en combinaison avec la fonction quantile. Le résultat s'obtient maintenant en qq secondes, donc oui, c'est réparé en qq sorte.

2023-08-21 18:32 UTC, frousseu commented on scripts/SDM/rangePredictions.yml
> +description: "This script computes the range of a 95% CI of a set of predictions rasters (from different models or from bootstrap/cross-validation procedures)."
J'ai changé CI pour confidence interval

2023-08-21 19:58 UTC, frousseu commented on .gitattributes
Ça fonctionne à partir d'un reclone, mais le mystère des fichiers avec whitespaces qui apparaissent demeure...

2023-08-24 18:02 UTC, jmlord approved these changes

2023-08-24 18:09 UTC, merged